"""Build export payloads for QueryNova results - Markdown, JSON, Notion formats."""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from io import BytesIO
from textwrap import wrap
from typing import Any, Dict, Iterable, List, Optional, Tuple

from src.utils.logger import logger


class ExportBuilder:
    """Build export bundles in multiple formats: Markdown, PDF, JSON, Notion."""

    def build_export_bundle(
        self,
        query: str,
        ranked: Iterable[Dict[str, Any]],
        summary: Optional[str],
        insights: Optional[List[str]],
        include_pdf: bool = False,
    ) -> Tuple[Dict[str, bytes], List[str]]:
        """
        Build complete export bundle with multiple format support.
        PDF export is disabled - focus on core features (Markdown, JSON, Notion).
        
        Args:
            query: The search query
            ranked: List of ranked results
            summary: AI-generated summary
            insights: List of key insights
            include_pdf: Ignored - PDF export disabled
        
        Returns:
            Tuple of (export_bundle dict, warnings list)
        """
        ranked_list = list(ranked)
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        
        # Build exports (no PDF)
        markdown = self._build_markdown(query, ranked_list, summary, insights, timestamp)
        json_payload = self._build_json(query, ranked_list, summary, insights, timestamp)
        notion = self._build_notion_payload(query, markdown)
        
        # Build bundle
        bundle: Dict[str, bytes] = {
            f"querynova_report_{timestamp}.md": markdown.encode("utf-8"),
            f"querynova_data_{timestamp}.json": json_payload,
            f"notion_export_{timestamp}.json": json.dumps(notion, indent=2).encode("utf-8"),
        }
        
        warnings: List[str] = []
        
        return bundle, warnings

    def _build_markdown(
        self,
        query: str,
        ranked: List[Dict[str, Any]],
        summary: Optional[str],
        insights: Optional[List[str]],
        timestamp: str,
    ) -> str:
        """Build comprehensive Markdown report."""
        lines = [
            "# 🔍 QueryNova Research Report",
            "",
            f"**Query:** {query}",
            f"**Generated:** {timestamp} UTC",
            f"**Results:** {len(ranked)} items",
            "",
            "---",
            "",
        ]
        
        # Executive Summary
        if summary:
            lines.extend([
                "## 📝 Executive Summary",
                "",
                summary,
                "",
            ])
        
        # Key Insights
        if insights:
            lines.extend([
                "## 💡 Key Insights",
                "",
            ])
            for insight in insights:
                lines.append(f"- {insight}")
            lines.append("")
        
        # Ranked Results
        lines.extend([
            "## 🎯 Ranked Results",
            "",
        ])
        
        for idx, item in enumerate(ranked, 1):
            title = item.get("title", "Untitled")
            url = item.get("url", "")
            score = item.get("score", 0)
            reliability = item.get("reliability", 0)
            item_summary = item.get("summary", "No summary available")
            insight = item.get("insight", "")
            
            lines.extend([
                f"### {idx}. {title}",
                "",
                f"**URL:** [{url}]({url})",
                f"**Relevance Score:** {score:.0%}",
                f"**Reliability:** {reliability:.0%}",
                "",
                f"**Summary:** {item_summary}",
                "",
            ])
            
            if insight:
                lines.extend([
                    f"**💡 Insight:** {insight}",
                    "",
                ])
            
            # Knowledge snippets
            snippets = item.get("snippets", [])
            if snippets:
                lines.append("**📚 Knowledge Base Context:**")
                for snippet in snippets:
                    lines.append(f"> {snippet.get('snippet', '')[:200]}")
                lines.append("")
        
        # Footer
        lines.extend([
            "---",
            "",
            "*Generated by QueryNova - AI-Powered Search Assistant*",
            "*Powered by SerpAPI × OpenAI × Streamlit Cloud*",
        ])
        
        return "\n".join(lines)

    def _build_json(
        self,
        query: str,
        ranked: List[Dict[str, Any]],
        summary: Optional[str],
        insights: Optional[List[str]],
        timestamp: str,
    ) -> bytes:
        """Build structured JSON export."""
        data = {
            "metadata": {
                "query": query,
                "generated_at": timestamp,
                "format_version": "2.0",
                "result_count": len(ranked),
            },
            "summary": summary,
            "insights": insights or [],
            "results": [
                {
                    "rank": idx,
                    "title": item.get("title", ""),
                    "url": item.get("url", ""),
                    "score": item.get("score", 0),
                    "reliability": item.get("reliability", 0),
                    "summary": item.get("summary", ""),
                    "insight": item.get("insight", ""),
                    "snippets": item.get("snippets", []),
                }
                for idx, item in enumerate(ranked, 1)
            ],
        }
        
        return json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")

    def _build_notion_payload(self, query: str, markdown: str) -> Dict[str, Any]:
        """
        Build Notion API-compatible payload.
        
        Note: Users need to replace 'YOUR_NOTION_DB_ID' with their actual database ID.
        """
        # Truncate markdown for Notion (max 2000 chars per block)
        truncated = markdown[:1900] if len(markdown) > 2000 else markdown
        
        return {
            "parent": {
                "type": "database_id",
                "database_id": "YOUR_NOTION_DB_ID",  # User must configure
            },
            "properties": {
                "Name": {
                    "title": [
                        {
                            "text": {
                                "content": f"QueryNova: {query[:80]}"
                            }
                        }
                    ]
                },
                "Tags": {
                    "multi_select": [
                        {"name": "QueryNova"},
                        {"name": "Research"},
                    ]
                },
            },
            "children": [
                {
                    "object": "block",
                    "type": "paragraph",
                    "paragraph": {
                        "rich_text": [
                            {
                                "type": "text",
                                "text": {
                                    "content": truncated
                                }
                            }
                        ]
                    },
                }
            ],
        }
